language: cpp
sudo: true
dist: trusty

compiler:
    - g++

#Build steps
before_install:
    - sudo apt-get install libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-net1.2-dev libcurl-dev libglu-dev -y

script: make LINUX=1